### ISSUE TITLE
高雄立绘

### ISSUE THREAD

**Issue by gqz8317** [taofan233/azurlane_uncensored#2]
6.25高雄立绘问题可使用日服立绘文件解决（无tex的那个）

[gaoxiong.zip](https://github.com/taofan233/azurlane_uncensored/files/4849440/gaoxiong.zip)

**Comment by taofan233** [comment]
高雄的立绘原版已经修复光环版是底包反和谐文件问题 底包会直接覆盖高雄立绘文件 只有修改了底包文件才能修复
