### ISSUE TITLE
使用说明有问题还是我用的有问题呢

### ISSUE THREAD

**Issue by liujingtech** [taofan233/azurlane_uncensored#21]
把 新泽西皮肤和谐版V2 按照使用方法（使用方法:解压并替换文件到Android/data/com.bilibili.azurlane/files），但是并没有效果，换到/files/AssetBundles/painting 也没有，用第三方工具看这个新泽西的皮肤好像还是原版，是不是文件本身有问题呀？

**Comment by taofan233** [comment]
> 把 新泽西皮肤和谐版V2 按照使用方法（使用方法:解压并替换文件到Android/data/com.bilibili.azurlane/files），但是并没有效果，换到/files/AssetBundles/painting 也没有，用第三方工具看这个新泽西的皮肤好像还是原版，是不是文件本身有问题呀？

应为这个和谐版就是原版,反和谐版在releases里
