### ISSUE TITLE
船名反和谐

### ISSUE THREAD

**Issue by Elypha** [taofan233/azurlane_uncensored#3]
您好，请问是否有办法还原日系船名？印象里之前曾经看到过一个昙花一现的改 `localization.txt` 文件的方法，不过不确定现在还行不行……

**Comment by taofan233** [comment]
localization修改只能解决立绘和特殊触摸,船名反和谐需要修改安装包或者scripts

**Comment by satoubako** [comment]
> localization修改只能解决立绘和特殊触摸,船名反和谐需要修改安装包或者scripts

請問可以麻煩說詳細一點嗎？具體要怎麼做呢(･o･;)

**Comment by taofan233** [comment]
> > localization修改只能解决立绘和特殊触摸,船名反和谐需要修改安装包或者scripts
> 
> 請問可以麻煩說詳細一點嗎？具體要怎麼做呢(･o･;)

我也不是很懂这方面的技术,修改安装包参考光环助手,修改scripts参考卖外挂的,如果研究成功了务必告知我lol

**Comment by satoubako** [comment]
🤣🤣光環上面的包現在也是原名了耶，超沒辦法的，謝謝啦！

2020年9月5日(土) 19:22 taofan233 <notifications@github.com>:
