### ISSUE TITLE
请问重樱船名有反和谐的方法吗

### ISSUE THREAD

**Issue by Elypha** [taofan233/azurlane_uncensored#30]
立绘反和谐倒是顺利成功了……
（记得以前是用光环助手，刚才去助手里看了一下貌似只有官方版了

**Comment by taofan233** [comment]
https://github.com/taofan233/azurlane_uncensored/issues/3

**Comment by taofan233** [comment]
目前还是无解

**Comment by Elypha** [comment]
（我竟然又回来了2333
明白了，谢谢
