### ISSUE TITLE
名字反和谐？

### ISSUE THREAD

**Issue by superwdy** [taofan233/azurlane_uncensored#4]
hi,

请问日文动物名有反和谐吗？

**Comment by taofan233** [comment]
在已解决的问题里有说明

**Comment by superwdy** [comment]
what do you mean by 已解决的问题? I can't find it anywhere.  not in the read me nor in the released files.

**Comment by taofan233** [comment]
https://github.com/taofan233/azurlane_uncensored/issues/3

**Comment by superwdy** [comment]
I see. 不好意思我用的是英文版， it's called closed issue.

Thanks a lot for the work!
